import 'dart:async';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import 'core/api_client.dart';import 'core/app_theme.dart';import 'core/auth_storage.dart';
import 'models/auth_models.dart';import 'models/call_models.dart';import 'models/task_models.dart';
import 'services/auth_api.dart';import 'services/calls_api.dart';import 'services/tasks_api.dart';
import 'widgets/empty_state.dart';import 'widgets/error_view.dart';import 'widgets/loading_view.dart';import 'widgets/status_badge.dart';

void main() => runApp(ChangeNotifierProvider(create: (_) => AppState()..init(), child: const SekurerApp()));
class SekurerApp extends StatelessWidget { const SekurerApp({super.key}); @override Widget build(BuildContext context)=>MaterialApp(title:'Sekurer',theme:buildAppTheme(),home:Consumer<AppState>(builder:(_,s,__)=>s.loading?const Scaffold(body:LoadingView()):(s.token==null?const AuthScreen():const HomeScreen()))); }
class AppState extends ChangeNotifier { final storage=AuthStorage(); late ApiClient api; String? token; bool loading=true; void init() async {api=ApiClient(storage,onUnauthorized:logout); token=await storage.getToken(); loading=false; notifyListeners();} Future<void> login(String e,String p) async {final t=await AuthApi(api).login(LoginRequest(email:e,password:p)); await storage.saveToken(t.accessToken); token=t.accessToken; notifyListeners();} Future<void> register(String n,String e,String p)=>AuthApi(api).register(RegisterRequest(name:n,email:e,password:p)); Future<void> logout() async {await storage.clearToken(); token=null; notifyListeners();}}
class AuthScreen extends StatefulWidget { const AuthScreen({super.key}); @override State<AuthScreen> createState()=>_AuthScreenState(); }
class _AuthScreenState extends State<AuthScreen>{bool reg=false,loading=false; final n=TextEditingController(),e=TextEditingController(),p=TextEditingController(); String? err; @override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:Text(reg?'Регистрация':'Вход')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[if(reg) TextField(controller:n,decoration:const InputDecoration(labelText:'Имя')),TextField(controller:e,decoration:const InputDecoration(labelText:'Email')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Пароль')),if(err!=null) Padding(padding:const EdgeInsets.only(top:8),child:Text(err!,style:const TextStyle(color:Colors.red))),const SizedBox(height:12),ElevatedButton(onPressed:loading?null:() async {setState((){loading=true;err=null;}); try{final s=context.read<AppState>(); if(reg){await s.register(n.text,e.text,p.text); await s.login(e.text,p.text);} else {await s.login(e.text,p.text);} } catch(ex){err=ex.toString();} setState((){loading=false;});}, child:Text(reg?'Зарегистрироваться':'Войти')),TextButton(onPressed:(){setState(()=>reg=!reg);}, child:Text(reg?'Уже есть аккаунт':'Создать аккаунт'))])));}}
class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen>{int idx=0; @override Widget build(BuildContext c){return Scaffold(body:idx==0?const CallsScreen():const PlannerScreen(),bottomNavigationBar:NavigationBar(selectedIndex: idx,onDestinationSelected:(v)=>setState(()=>idx=v),destinations:const [NavigationDestination(icon:Icon(Icons.call), label:'Звонки'),NavigationDestination(icon:Icon(Icons.event_note), label:'Планировщик')]));}}
class CallsScreen extends StatefulWidget { const CallsScreen({super.key}); @override State<CallsScreen> createState()=>_CallsScreenState(); }
class _CallsScreenState extends State<CallsScreen>{List<CallListItem>? data; String? err; @override void initState(){super.initState();load();} Future<void> load() async {try{data=await CallsApi(context.read<AppState>().api).listCalls(); err=null;}catch(e){err=e.toString();} if(mounted)setState((){});} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Sekurer'),actions:[IconButton(onPressed:()=>context.read<AppState>().logout(),icon:const Icon(Icons.logout))]),floatingActionButton:FloatingActionButton(onPressed:() async {await Navigator.push(c,MaterialPageRoute(builder:(_)=>const UploadScreen())); await load();},child:const Icon(Icons.add)),body:RefreshIndicator(onRefresh:load,child:err!=null?ListView(children:[SizedBox(height:500,child:ErrorView(message:err!,onRetry:load))]):(data==null?const LoadingView():data!.isEmpty?const EmptyState(title:'Записей пока нет', subtitle:'Добавьте запись звонка, чтобы получить договорённости и задачи'):ListView.builder(itemCount:data!.length,itemBuilder:(_,i){final it=data![i]; return Card(child:ListTile(title:Text(it.title??'Без названия'),subtitle:Text('${it.contactName??'—'} • ${DateFormat('dd.MM.yyyy HH:mm').format(it.createdAt.toLocal())}'),trailing:StatusBadge(status:it.status),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>CallDetailScreen(callId:it.id)))));}))));}
class UploadScreen extends StatefulWidget { const UploadScreen({super.key}); @override State<UploadScreen> createState()=>_UploadScreenState(); }
class _UploadScreenState extends State<UploadScreen>{final t=TextEditingController(),cn=TextEditingController(),pn=TextEditingController(); File? f; String? err; bool loading=false; @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Добавить запись')),body:Padding(padding:const EdgeInsets.all(16),child:ListView(children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Название')),TextField(controller:cn,decoration:const InputDecoration(labelText:'Контакт')),TextField(controller:pn,decoration:const InputDecoration(labelText:'Телефон')),const SizedBox(height:8),OutlinedButton(onPressed:() async {final r=await FilePicker.platform.pickFiles(type: FileType.custom,allowedExtensions:['mp3','m4a','wav','aac','ogg','webm']); if(r!=null&&r.files.single.path!=null)setState(()=>f=File(r.files.single.path!));}, child:Text(f==null?'Выбрать аудиофайл':f!.path.split('/').last)),if(err!=null) Text(err!,style:const TextStyle(color:Colors.red)),const SizedBox(height:12),ElevatedButton(onPressed:loading?null:() async {if(f==null){setState(()=>err='Выберите файл');return;} setState((){loading=true;err=null;}); try{final id=await CallsApi(context.read<AppState>().api).uploadCall(f!,title:t.text,contactName:cn.text,phoneNumber:pn.text); if(!c.mounted)return; Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>CallDetailScreen(callId:id)));} catch(e){setState(()=>err=e.toString());} setState(()=>loading=false);}, child:Text(loading?'Загрузка...':'Загрузить'))])));
}
class CallDetailScreen extends StatefulWidget { final String callId; const CallDetailScreen({super.key, required this.callId}); @override State<CallDetailScreen> createState()=>_CallDetailScreenState(); }
class _CallDetailScreenState extends State<CallDetailScreen>{CallDetail? d; Timer? timer; String? err; @override void initState(){super.initState();load();} @override void dispose(){timer?.cancel();super.dispose();} Future<void> load() async {try{d=await CallsApi(context.read<AppState>().api).getCall(widget.callId); err=null; if(['uploaded','transcribing','analyzing'].contains(d!.status)){timer?.cancel(); timer=Timer.periodic(const Duration(seconds:2),(_)=>load());} else {timer?.cancel();}}catch(e){err=e.toString();} if(mounted)setState((){});} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Детали звонка')),body:err!=null?ErrorView(message:err!,onRetry:load):d==null?const LoadingView():ListView(padding:const EdgeInsets.all(12),children:[Text(d!.title??'Без названия',style:Theme.of(c).textTheme.titleLarge),Text(d!.contactName??'—'),StatusBadge(status:d!.status),if(['uploaded','transcribing','analyzing'].contains(d!.status)) const Padding(padding:EdgeInsets.symmetric(vertical:8),child:Text('Идёт обработка...')),if(d!.status=='failed') ElevatedButton(onPressed:() async {await CallsApi(context.read<AppState>().api).retry(widget.callId); load();}, child:const Text('Повторить обработку')),if(d!.summary!=null) Card(child:ListTile(title:const Text('Кратко'),subtitle:Text(d!.summary!))),...d!.tasks.map((t)=>Card(child:ListTile(title:Text(t.title),subtitle:Text(t.status),trailing:Wrap(spacing:4,children:[TextButton(onPressed:()=>upd(t.id,{'status':'confirmed','requires_confirmation':false}), child:const Text('Подтвердить')),TextButton(onPressed:()=>upd(t.id,{'status':'done'}), child:const Text('Выполнено')),TextButton(onPressed:()=>upd(t.id,{'status':'cancelled'}), child:const Text('Отменить'))])))),ExpansionTile(title:const Text('Транскрипт'),children:[Padding(padding:const EdgeInsets.all(12),child:Text(d!.transcript??'Нет транскрипта'))]) ])); Future<void> upd(String id,Map<String,dynamic> p) async {await TasksApi(context.read<AppState>().api).updateTask(id,p); load();}}
class PlannerScreen extends StatefulWidget { const PlannerScreen({super.key}); @override State<PlannerScreen> createState()=>_PlannerScreenState(); }
class _PlannerScreenState extends State<PlannerScreen>{List<TaskModel>? t; String f='all'; @override void initState(){super.initState();load();} Future<void> load() async {t=await TasksApi(context.read<AppState>().api).listTasks(); if(mounted)setState((){});} @override Widget build(BuildContext c){if(t==null)return const LoadingView(); final list=t!.where((x){if(f=='draft')return x.status=='draft';if(f=='confirmed')return x.status=='confirmed';if(f=='done')return x.status=='done';return true;}).toList(); return Scaffold(appBar:AppBar(title:const Text('Планировщик')),body:Column(children:[Wrap(spacing:6,children:[for(final e in const {'all':'Все','draft':'Черновики','confirmed':'Подтверждённые','done':'Выполненные'}.entries) ChoiceChip(label:Text(e.value),selected:f==e.key,onSelected:(_)=>setState(()=>f=e.key))]),Expanded(child:list.isEmpty?const EmptyState(title:'Нет задач', subtitle:'Задачи появятся после анализа звонка'):ListView(children:list.map((x)=>Card(child:ListTile(title:Text(x.title),subtitle:Text('${x.status} • ${x.dueDate?.toIso8601String().split('T').first ?? 'без срока'}'),trailing:TextButton(onPressed:() async {await TasksApi(context.read<AppState>().api).updateTask(x.id, {'status':'done'}); load();}, child:const Text('Выполнено'))))).toList()))])); }}
